wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1642174121
    t:
      1:
      - 1
      - 5
      - 9
      3:
      - 13
      4: 3.8.12
      5: 0.12.9
      8:
      - 5
